spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://planmanager-db.c5ky8g0ccs0m.ap-northeast-2.rds.amazonaws.com:3306/planmanager?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: zxdasc12
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: "v3ry-l0ng-s3cr3t-k3y-f0r-plan-manager-s3rv3r-applicati0n-s3cur1ty-updat3d"
  # 만료 시간을 밀리초(ms) 단위로 설정합니다. (예: 86400000 = 24시간)
  # 코드에 long 타입으로 선언되어 있을 확률이 높으므로 숫자로 적습니다.
  expiration: 86400000